version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}testdocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    networks:
      - reverse-proxy
      - back
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=test.anhdh.com
      - LETSENCRYPT_HOST=test.anhdh.com
      - LETSENCRYPT_EMAIL=anhdhbn@gmail.com
#    volumes:
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
#      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge 
