version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}testdocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    networks:
      - reverse-proxy
      - back
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=test.anhdh.com
      - LETSENCRYPT_HOST=test.anhdh.com
      - LETSENCRYPT_EMAIL=anhdhbn@gmail.com

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge 
